name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      percentage-rollout:
        description: 'Should we use a percentage rollout?'
        required: true
        default: 'false'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Percentage rollout? ${{ github.event.inputs.percentage-rollout }}!"
